language: java
# Test compilation with JDK6 since it seems to cause problems with fonts
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
# Coverity
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Tfi7wgekq3HOVhLksw7tpEoB4rFTYbcmzzTcXwD9J9SOlCm48u8DTpsvCEhsAIY+91AWNVu+abtPKaufwXvlpxpjnMTYMMwpLpLlYlhyDkW7IXRn5svD5XB8v9sqGVx5r2AN1koZI3beg3l1VrjAktK58atXZBHPmJ2DUgOOILc="
addons:
  coverity_scan:
    project:
      name: "cyChop/daily-tasks"
      description: "Build submitted via Travis CI"
    notification_email: cyrille.chopelet@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
